apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-emh1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-emh1
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-emh1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-emh1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-emh1
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dzrs-tenant/rhtap-demo-app/hacbs-test-project-emh1@sha256:bfca78bb0a19d3217107e8c5fad2aaee42dac6249a051c0cd399aed84cc9d436
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
